spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/equipos
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver
        
logging.level.org.springframework.jdbc.core: TRACE

